name: Add Link
description: Suggest new link to be added to hyperlink.cafe
title: "[Content/link] Add link to ..."
labels: content/link
body:
  - type: markdown
    attributes:
      value: |
        Only the site Title and URL is **required**. All other fields are optional.
  - type: input
    id: title
    attributes:
      label: Site Title
      description: The home page of the live web site.
      placeholder: e.g. Autumns Digital Garden
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Site Links Page URL
      description: The url of your links page. _[parser:url]_
      placeholder: e.g. https://www.photogabble.co.uk/links
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Site Source URL
      description: If open source, include link to code repository _[parser:url]_
      placeholder: e.g. https://www.github.com/photogabble/website
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Website description"
      description: "Optional: _you can leave this empty if you like_"
      placeholder: e.g. Personal website and digital garden of a professional coffee drinker...
    validations:
      required: false